<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress_logger"
 *
 * Auto generated by Extension Builder 2017-12-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

/** @noinspection PhpUndefinedVariableInspection */
$EM_CONF[$_EXTKEY] = [
    'title' => 'Registeraddress Logger',
    'description' => 'Add logging to registeraddress to full fill law needs  ',
    'category' => 'plugin',
    'author' => 'Eike Starkmann',
    'author_email' => 'es@undkonsorten.com',
    'state' => 'stable',
    'version' => '1.2.1',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0 - 11.5.99',
            'registeraddress' => '2.0.0-2.99.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
