<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress_logger"
 *
 * Auto generated by Extension Builder 2017-12-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

/** @noinspection PhpUndefinedVariableInspection */
$EM_CONF[$_EXTKEY] = [
    'title' => 'Registeraddress Logger',
    'description' => 'Add logging to registeraddress to full fill law needs  ',
    'category' => 'plugin',
    'author' => 'Eike Starkmann',
    'author_email' => 'es@undkonsorten.com',
    'state' => 'stable',
    'version' => '1.2.2',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0 - 12.4.00',
            'registeraddress' => '5.0.0 - 5.99.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
