<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress_logger"
 *
 * Auto generated by Extension Builder 2017-12-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Registeraddress Logger',
    'description' => 'Add logging to registeraddress to full fill law needs  ',
    'category' => 'plugin',
    'author' => 'Eike Starkmann',
    'author_email' => 'es@undkonsorten.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.7.99',
            'registeraddress' => '1.0.13-1.0.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
