services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Undkonsorten\RegisteraddressLogger\:
    resource: '../Classes/*'

  Undkonsorten\RegisteraddressLogger\EventListener\DeleteEventListener:
    tags:
      - name: event.listener
        identifier: 'register-address-delete-log-event'
  Undkonsorten\RegisteraddressLogger\EventListener\LogApproveEventListener:
    tags:
      - name: event.listener
        identifier: 'register-address-approve-before-log-event'
        method: 'logApprove'
  Undkonsorten\RegisteraddressLogger\EventListener\LogCreateEventListener:
    tags:
      - name: event.listener
        identifier: 'register-address-create-before-log-event'
        method: 'logCreate'
  Undkonsorten\RegisteraddressLogger\EventListener\LogDeleteEventListener:
    tags:
      - name: event.listener
        identifier: 'register-address-delete-before-log-event'
        method: 'logDelete'
  Undkonsorten\RegisteraddressLogger\EventListener\LogUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'register-address-update-before-log-event'
        method: 'logUpdate'

